source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'HMSegmentedControl', '~> 1.5.2'
pod 'THSegmentedPager', :path=> '../../THSegmentedPager'

target 'THSegmentedPagerExampleTests', :exclusive => true do
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  pod 'Specta'
  pod 'Expecta'
end
